Update red_teaming.json
noraj/rawsec-cybersecurity-inventory pull request #17
Opened 2020-10-07 07:37 UTC by WulfPlasma

Added King Phisher and Gophish

2020-10-07 07:40 UTC, WulfPlasma commented
@noraj lmk if everything looks good and you're ready to merge.

2020-10-07 18:17 UTC, merged

2020-10-07 18:18 UTC, noraj requested changes
I fixed all that in 5020dedef07ef51b154419f9ea4339134dbd4999 for this time, so you don't need to update it.
Thanks for your contribution.

2020-10-07 18:18 UTC, noraj commented on data/tools/red_teaming.json
> +      "name": "King Phisher",
You have to sort them alphabetically. see [Format conventions](https://inventory.raw.pm/docs/docs/en/format/) & [Adding/changing content](https://inventory.raw.pm/docs/docs/en/add/#addingchanging-content)

2020-10-07 18:18 UTC, noraj commented on data/tools/red_teaming.json
> +    },
extra comma

2020-10-07 18:18 UTC, noraj commented on data/tools/red_teaming.json
> +      "source": "https://getgophish.com/",
this is the website, not the source repo

2020-10-07 18:18 UTC, noraj commented on data/tools/red_teaming.json
> +      "description": "Gophish is an open-source phishing toolkit designed for businesses and penetration testers. It provides the ability to quickly and easily setup and execute phishing engagements
Format conventions of teh description does not contains tool name, etc.
Do not only copy paste the disclaimer of the tool.

2020-10-07 20:20 UTC, WulfPlasma commented
Thank you for letting me work on this, I’ll keep everything in mind that was fixed if I contribute again.

2020-10-08 22:59 UTC, WulfPlasma commented
@noraj does it still count as invalid even though it was merged?

2020-10-09 09:27 UTC, noraj commented
Yeah I tagged it as invalid because I had too much change to do to make it follow [Format conventions](https://inventory.raw.pm/docs/docs/en/format/) & [Adding/changing content](https://inventory.raw.pm/docs/docs/en/add/#addingchanging-content).
Please follow those guidelines for your next contributions :smiley: