add osquery tool to incident_response.json
noraj/rawsec-cybersecurity-inventory pull request #51
Opened 2024-03-22 07:17 UTC by nadasuhailAyesh12

2024-03-23 21:39 UTC, noraj requested changes
Thanks for the contrib

2024-03-23 21:39 UTC, noraj commented on data/tools/incident_response.json
> +    ,
```suggestion
```

2024-03-23 21:39 UTC, noraj commented on data/tools/incident_response.json
> +    }
```suggestion
    },
```

2024-03-23 21:39 UTC, noraj commented on data/tools/incident_response.json
> +      "description": "Endpoint visibility tool providing SQL-based querying for monitoring and security analysis of operating systems.",
```suggestion
      "description": "Endpoint visibility tool providing SQL-based querying for monitoring and security analysis of operating systems",
```

2024-03-23 21:39 UTC, noraj commented on data/tools/incident_response.json
> +      "language": "C++",
```suggestion
      "language": "Cplusplus",
```

> The language field value should match [Font Mfizz](http://fizzed.com/oss/font-mfizz) Programming languages name when it exists and be capitalized
>
> Example: Cplusplus for C++ or Nodejs for Node.js

https://inventory.raw.pm/docs/docs/contribution_guidelines/format.html

2024-03-24 04:50 UTC, nadasuhailAyesh12 commented
I have updated the changes.Can you please take a look @noraj

2024-03-24 15:18 UTC, noraj commented
@nadasuhailAyesh12 Thanks for your contribution, I'll happily accept new pull request in the future.

2024-03-24 15:33 UTC, noraj commented
I squash-merged it here: https://github.com/noraj/rawsec-cybersecurity-inventory/commit/8538d01bc83907e173c539066faeb7ba99edf1a4

2024-03-24 15:33 UTC, closed without merging

2024-03-24 15:42 UTC, noraj commented
https://twitter.com/rawsec_cyber/status/1771925413951918375